import Layout from '@/Components/Layout'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })
export const metadata = {
    title: 'Todo App DashBoard',
    description: 'Generated by Morteza Kia',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
          <body className={inter.className}>
            <Layout>
                {children}
            </Layout>
          </body>
        </html>
    )
  }
  